/* Browser checks against the isolated local fixture, never production storage. */
const fs = require('fs');
const path = require('path');
const assert = require('assert/strict');
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
(async () => {
  const output = path.resolve(process.env.MEDCHEM_QA_OUTPUT || 'data/e099-ui');
  fs.mkdirSync(output, {recursive:true});
  const fixture = JSON.parse(fs.readFileSync(path.resolve('data/e098-ui/server.json'), 'utf8'));
  const browser = await chromium.launch({channel: 'msedge', headless: true});
  try {
    const page = await browser.newPage({viewport: {width: 1440, height: 1100}});
    const sessionResponse = await page.request.post(fixture.url + '/api/session', {
      headers: {'Authorization':'Bearer isolated-ui-fixture'}, data: {}
    });
    assert.equal(sessionResponse.ok(), true);
    const freshSession = (await sessionResponse.json()).session;
    const errors = [];
    page.on('pageerror', error => errors.push(error.message));
    await page.goto(fixture.url + '/#token=isolated-ui-fixture&session=' + freshSession);
    await page.waitForFunction(() => document.getElementById('connection').textContent === 'Connected');
    await page.waitForFunction(() => [...document.images].every(img => img.complete && img.naturalWidth > 0));
    assert.equal(await page.title(), 'MEDCHEM Agent');
    assert.equal(await page.locator('#coverage-menu').getAttribute('open'), null);
    assert.equal(await page.locator('#results-menu').evaluate(el => el.open), false);
    assert.equal(await page.locator('.hero').innerText(), 'ME\nCHEM\nAgent');
    await page.screenshot({path: path.join(output, 'desktop.png'), fullPage: true});
    await page.locator('.masthead').screenshot({path:path.join(output,'masthead.png')});
    await page.setViewportSize({width:390,height:844});
    await page.screenshot({path:path.join(output,'mobile.png'),fullPage:true});
    await page.setViewportSize({width:1440,height:1100});
    await page.locator('#results-menu > summary').hover();
    assert.equal(await page.locator('#results-menu').evaluate(el => el.open), true);
    await page.locator('#results-panel').hover();
    await page.waitForTimeout(250);
    assert.equal(await page.locator('#results-menu').evaluate(el => el.open), true);
    await page.screenshot({path: path.join(output, 'results.png'), fullPage: true});
    await page.locator('h1').hover();
    await page.waitForTimeout(250);
    assert.equal(await page.locator('#results-menu').evaluate(el => el.open), false);
    await page.locator('#results-menu > summary').focus();
    assert.equal(await page.locator('#results-menu').evaluate(el => el.open), true);
    await page.keyboard.press('Escape');
    assert.equal(await page.locator('#results-menu').evaluate(el => el.open), false);
    await page.locator('#coverage-menu summary').hover();
    assert.equal(await page.locator('#coverage-menu').evaluate(el => el.open), true);
    await page.locator('.coverage-panel').hover();
    assert.equal(await page.locator('#coverage-menu').evaluate(el => el.open), true);
    await page.screenshot({path: path.join(output, 'coverage.png'), fullPage: true});
    await page.locator('h1').hover();
    assert.equal(await page.locator('#coverage-menu').evaluate(el => el.open), false);
    await page.locator('#coverage-menu summary').focus();
    assert.equal(await page.locator('#coverage-menu').evaluate(el => el.open), true);
    await page.keyboard.press('Escape');
    assert.equal(await page.locator('#coverage-menu').evaluate(el => el.open), false);
    await page.getByRole('button', {name: 'Review docking results', exact: true}).click();
    assert.match(await page.locator('#prompt').inputValue(), /attached docking/);
    assert.equal(await page.locator('.message.user').count(), 0);
    await page.locator('#prompt').fill('/capabilities');
    await page.getByRole('button', {name: 'Send message'}).click();
    await page.waitForFunction(() => document.getElementById('messages').textContent.includes('Completed docking results:'));
    await page.reload();
    await page.waitForFunction(() => document.getElementById('messages').textContent.includes('/capabilities'));
    await page.locator('#results-menu > summary').click();
    await page.locator('h1').hover();
    await page.waitForTimeout(250);
    assert.equal(await page.locator('#results-menu').evaluate(el => el.open), true);
    await page.getByText('Attach an existing result', {exact: true}).click();
    await page.locator('#attachment-kind').selectOption('plan');
    assert.equal(await page.locator('#existing-label').textContent(), 'Existing plan.json path');
    await page.locator('#attachment-kind').selectOption('docking');
    assert.equal(await page.locator('#existing-label').textContent(), 'PLANTS report.json path');
    await page.locator('#close-results').click();
    assert.equal(await page.locator('#results-menu').evaluate(el => el.open), false);
    await page.setViewportSize({width: 390, height: 844});
    await page.screenshot({path: path.join(output, 'mobile-conversation.png'), fullPage: true});
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
    await page.locator('#coverage-menu summary').click();
    assert.equal(await page.locator('#coverage-menu').evaluate(el => el.open), true);
    await page.locator('#results-menu > summary').click();
    assert.equal(await page.locator('#results-menu').evaluate(el => el.open), true);
    const bounds=await page.locator('#results-panel').boundingBox();
    assert.ok(bounds.x >= 0 && bounds.x + bounds.width <= 390);
    await page.screenshot({path:path.join(output,'mobile-results.png'),fullPage:true});
    await page.locator('#close-results').click();
    assert.equal(await page.locator('#results-menu').evaluate(el => el.open), false);
    const touch=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});
    await touch.goto(fixture.url+'/#token=isolated-ui-fixture&session='+freshSession);
    await touch.waitForFunction(()=>document.getElementById('messages').textContent.includes('/capabilities'));
    await touch.locator('#results-menu > summary').tap();
    assert.equal(await touch.locator('#results-menu').evaluate(el=>el.open),true);
    await touch.locator('#close-results').tap();
    assert.equal(await touch.locator('#results-menu').evaluate(el=>el.open),false);
    await touch.close();
    assert.deepEqual(errors, []);
    fs.writeFileSync(path.join(output, 'report.json'), JSON.stringify({status:'passed', desktop:[1440,1100], mobile:[390,844], checks:['assets','branding','hover','focus','escape','click','draft-only examples','message submission','session persistence','attachment types','no horizontal overflow','no JS errors','results hover preview','results pin','results escape and close','mobile results drawer','minimal hero copy'], scientific_data:'isolated fixture only'}, null, 2));
    console.log('MEDCHEM browser checks passed');
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
